#!/bin/sh
#
# carpald
#
# description: carpald is a program which wakes up every so often and 
#              tells us that we need to take a break from the keyboard 
#              or we'll lose all functinality of our wrists and never be 
#              able to type again as long as we live.
# chkconfig: 35 99 01

[ -f /usr/local/sbin/carpald.sh ] || exit 0

# source function library
. /etc/init.d/functions

case "$1" in 
  start) 
         echo -n "Starting carpald: "
         daemon /usr/local/sbin/carpald.sh &
         echo -n "done"
         touch /var/lock/subsys/carpald
         ;;
  stop)  
         echo -n "Stopping carpald services: "
         killproc /usr/local/sbin/carpald.sh
         echo -n "done"
         rm -f /var/lock/subsys/carpald
         ;;
  status) 
         status /usr/local/sbin/carpald.sh
         ;;
  restart|reload)
         $0 stop
         $0 start
         ;;
  *)
         echo "Usage: carpal {start|stop|status|restart|reload}"
         exit 1
	 ;;
esac
exit 0
